In [2]:
import pandas as pd
import numpy as np
from sympy.physics.units import length

# Exploration

In [ ]:
airbnb = pd.read_csv("data/airbnb_train.csv")
airbnb.head()
print("coucou Antsa")

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,last_review,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5708593,4.317488,House,Private room,"{TV,""Wireless Internet"",Kitchen,""Free parking ...",3,1.0,Real Bed,flexible,False,...,NaN,33.782712,-118.134410,Island style Spa Studio,Long Beach,0,NaN,90804,0.0,2.0
1,14483613,4.007333,House,Private room,"{""Wireless Internet"",""Air conditioning"",Kitche...",4,2.0,Real Bed,strict,False,...,2017-09-17,40.705468,-73.909439,"Beautiful and Simple Room W/2 Beds, 25 Mins to...",Ridgewood,38,86.0,11385,1.0,2.0
2,10412649,7.090077,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",6,2.0,Real Bed,flexible,False,...,NaN,38.917537,-77.031651,2br/2ba luxury condo perfect for infant / toddler,U Street Corridor,0,NaN,20009,2.0,2.0
3,17954362,3.555348,House,Private room,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",1,1.0,Real Bed,flexible,True,...,2017-09-29,40.736001,-73.924248,Manhattan view from Queens. Lovely single room .,Sunnyside,19,96.0,11104,1.0,1.0
4,9969781,5.480639,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,moderate,True,...,2017-08-28,37.744896,-122.430665,Zen Captured Noe Valley House,Noe Valley,15,96.0,94131,2.0,2.0

In [4]:
print("Colonnes du dataset :")
airbnb.columns

print(f"Taille du dataset : {len(airbnb)}")

Colonnes du dataset :
Taille du dataset : 22234

Type de données contenues dans le dataset

In [13]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22234 entries, 0 to 22233
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      22234 non-null  int64
 1   log_price               22234 non-null  float64
 2   property_type           22234 non-null  object
 3   room_type               22234 non-null  object
 4   amenities               22234 non-null  object
 5   accommodates            22234 non-null  int64
 6   bathrooms               22234 non-null  float64
 7   bed_type                22234 non-null  object
 8   cancellation_policy     22234 non-null  object
 9   cleaning_fee            22234 non-null  object
 10  city                    22234 non-null  object
 11  description             22234 non-null  object
 12  first_review            17517 non-null  object
 13  host_has_profile_pic    22178 non-null  object
 14  host_identity_verified  22178 non-null  object
 15  host_response_rate      16774 non-null  object
 16  host_since              22178 non-null  object
 17  instant_bookable        22234 non-null  object
 18  last_review             17526 non-null  object
 19  latitude                22234 non-null  float64
 20  longitude               22234 non-null  float64
 21  name                    22234 non-null  object
 22  neighbourhood           20149 non-null  object
 23  number_of_reviews       22234 non-null  int64
 24  review_scores_rating    17264 non-null  float64
 25  zipcode                 21931 non-null  object
 26  bedrooms                22208 non-null  float64
 27  beds                    22208 non-null  float64
dtypes: float64(7), int64(3), object(18)
memory usage: 4.7+ MB

On voit que la majorité des données stockées sont de type 'object'.

Nombre de valeurs nulles dans le dataset (par colonne)

In [30]:
airbnb.isnull().sum()

id                           0
log_price                    0
property_type                0
room_type                    0
amenities                    0
accommodates                 0
bathrooms                    0
bed_type                     0
cancellation_policy          0
cleaning_fee                 0
city                         0
description                  0
first_review              4717
host_has_profile_pic        56
host_identity_verified      56
host_response_rate        5460
host_since                  56
instant_bookable             0
last_review               4708
latitude                     0
longitude                    0
name                         0
neighbourhood             2085
number_of_reviews            0
review_scores_rating      4970
zipcode                    303
bedrooms                    26
beds                        26
dtype: int64

Liste des colonnes dans lesquelles il y a des valeurs nulles

In [31]:
airbnb.columns[airbnb.isnull().any()]

Index(['first_review', 'host_has_profile_pic', 'host_identity_verified',
       'host_response_rate', 'host_since', 'last_review', 'neighbourhood',
       'review_scores_rating', 'zipcode', 'bedrooms', 'beds'],
      dtype='object')

On remarque que dans les colonnes first_review, host_response_rate et last_review, les valeurs nulles sont importantes. On va donc regarder le pourcentage de valeurs nulles pour ces colonnes.

In [38]:
n = len(airbnb)

print(f"Pourcentage de valeurs nulles dans 'first_review' : {airbnb['first_review'].isnull().sum()/n}")
print(f"Pourcentage de valeurs nulles dans 'host_response_rate' : {airbnb['host_response_rate'].isnull().sum()/n}")
print(f"Pourcentage de valeurs nulles dans 'last_review' : {airbnb['last_review'].isnull().sum()/n}")

Pourcentage de valeurs nulles dans 'first_review' : 0.21215255914365386
Pourcentage de valeurs nulles dans 'host_response_rate' : 0.2455698479805703
Pourcentage de valeurs nulles dans 'last_review' : 0.21174777367994962

Le pourcentage de valeurs nulles étant assez important, on décide donc de drop les colonnes concernées.

In [39]:
airbnb.drop(["first_review", "host_response_rate", "last_review"], axis=1, inplace=True)

Affichage de statistiques génériques (count, moyenne, écart-type, nombre d'élements uniques...)

In [15]:
airbnb.describe(include="all")

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,last_review,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
count,2.223400e+04,22234.000000,22234.0,22234,22234,22234.000000,22234.000000,22234,22234,22234,...,17526,22234.000000,22234.000000,22234.0,20149,22234.000000,17264.000000,21931,22208.000000,22208.000000
unique,NaN,NaN,31.0,4,21119,NaN,NaN,6,6,2,...,1039,NaN,NaN,22105.0,559,NaN,NaN,675,NaN,NaN
top,NaN,NaN,1.0,Entire home/apt,{},NaN,NaN,Real Bed,strict,True,...,2017-04-30,NaN,NaN,0.0,Williamsburg,NaN,NaN,11211.0,NaN,NaN
freq,NaN,NaN,14601.0,12328,158,NaN,NaN,21572,9702,16377,...,419,NaN,NaN,51.0,878,NaN,NaN,425,NaN,NaN
mean,1.119351e+07,4.772788,NaN,NaN,NaN,3.150040,1.233201,NaN,NaN,NaN,...,NaN,38.374410,-92.063793,NaN,NaN,20.595125,93.795181,NaN,1.262068,1.708438
std,6.097074e+06,0.753662,NaN,NaN,NaN,2.147838,0.588551,NaN,NaN,NaN,...,NaN,3.577633,22.092124,NaN,NaN,37.134816,9.299268,NaN,0.854497,1.256803
min,0.000000e+00,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,...,NaN,0.000000,-122.510940,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000
25%,6.145774e+06,4.304065,NaN,NaN,NaN,2.000000,1.000000,NaN,NaN,NaN,...,NaN,34.132370,-118.340275,NaN,NaN,1.000000,92.000000,NaN,1.000000,1.000000
50%,1.213483e+07,4.700480,NaN,NaN,NaN,2.000000,1.000000,NaN,NaN,NaN,...,NaN,40.661546,-76.993512,NaN,NaN,6.000000,96.000000,NaN,1.000000,1.000000
75%,1.638861e+07,5.220356,NaN,NaN,NaN,4.000000,1.000000,NaN,NaN,NaN,...,NaN,40.746188,-73.954373,NaN,NaN,23.000000,100.000000,NaN,1.000000,2.000000
max,2.120450e+07,7.600402,NaN,NaN,NaN,16.000000,8.000000,NaN,NaN,NaN,...,NaN,42.390248,0.000000,NaN,NaN,505.000000,100.000000,NaN,10.000000,18.000000

On remarque que pour certaines colonnes (bed_type, host_identity_verified par ex.), il y a une valeur qui ressort souvent. Dans les parties qui vont suivre, on va essayer de voir la fréquence d'apparition de ces valeurs afin de les éliminer ou non.

Fréquence d'apparition des valeurs dites 'top' dans les colonnes éligibles

In [23]:
n = len(airbnb)

print(f"Pourcentage d'apparition de 'Real Bed' dans bed_type : {sum(airbnb[airbnb['bed_type'] == 'Real Bed'].count())/n}")
print(f"Pourcentage d'apparition de 'Entire home/apartment' dans room_type : {sum(airbnb[airbnb['room_type'] == 'Entire home/apartment'].count())/n}")
print(f"Pourcentage d'apparition de 'strict' dans bed_type : {sum(airbnb[airbnb['cancellation_policy'] == 'strict'].count())/n}")
print(f"Pourcentage d'apparition de 'True' dans cleaning_fee : {sum(airbnb[airbnb['cleaning_fee'] == True].count())/n}")
print(f"Pourcentage d'apparition de 't' dans host_has_profile_pic : {sum(airbnb[airbnb['host_has_profile_pic'] == 't'].count())/n}")
print(f"Pourcentage d'apparition de 't' dans host_identity_verified : {sum(airbnb[airbnb['host_identity_verified'] == 't'].count())/n}")
print(f"Pourcentage d'apparition de '100%' dans host_response_rate : {sum(airbnb[airbnb['host_response_rate'] == '100%'].count())/n}")
print(f"Pourcentage d'apparition de 'f' dans instant_bookable : {sum(airbnb[airbnb['instant_bookable'] == 'f'].count())/n}")
print(f"Pourcentage d'apparition de 'Williamsburg' dans neighbourhood : {sum(airbnb[airbnb['neighbourhood'] == 'Williamsburg'].count())/n}")

Pourcentage d'apparition de 'Real Bed' dans bed_type : 26.18597643249078
Pourcentage d'apparition de 'Entire home/apartment' dans room_type : 0.0
Pourcentage d'apparition de 'strict' dans bed_type : 11.934559683367816
Pourcentage d'apparition de 'True' dans cleaning_fee : 20.057839345147073
Pourcentage d'apparition de 't' dans host_has_profile_pic : 26.78730772690474
Pourcentage d'apparition de 't' dans host_identity_verified : 18.267248358370065
Pourcentage d'apparition de '100%' dans host_response_rate : 16.124404065845102
Pourcentage d'apparition de 'f' dans instant_bookable : 19.81128002158856
Pourcentage d'apparition de 'Williamsburg' dans neighbourhood : 1.0680039579023117

On remarque que certains pourcentages sont très importants

Vérification des colonnes dont le contenu ne peut pas être traité par un algorithme

In [5]:
rooms = airbnb["room_type"].unique()
beds_type = airbnb["bed_type"].unique()
answer_rate = airbnb["host_response_rate"].unique()
pfp = airbnb["host_has_profile_pic"].unique()
cancellation = airbnb["cancellation_policy"].unique()
verified = airbnb["host_identity_verified"].unique()
online_booking = airbnb["instant_bookable"].unique()
cities = airbnb["city"].unique()

print(f"Type de chambres : {rooms}")
print(f"Type de lits : {beds_type}")
print(f"Temps de réponse : {answer_rate}")
print(f"Présence de photo de profil : {pfp}")
print(f"Conditions d'annulation : {cancellation}")
print(f"Identité vérifiée : {verified}")
print(f"Réservation en ligne : {online_booking}")
print(f"Villes : {cities}")

Type de chambres : ['Private room' 'Entire home/apt' 'Shared room']
Type de lits : ['Real Bed' 'Pull-out Sofa' 'Futon' 'Airbed' 'Couch']
Temps de réponse : [nan '100%' '80%' '86%' '90%' '89%' '40%' '81%' '70%' '99%' '0%' '20%'
 '67%' '56%' '43%' '75%' '94%' '88%' '95%' '60%' '83%' '78%' '96%' '50%'
 '87%' '97%' '91%' '79%' '98%' '63%' '71%' '93%' '92%' '64%' '42%' '82%'
 '25%' '33%' '54%' '73%' '57%' '58%' '17%' '30%' '85%' '53%' '44%' '31%'
 '77%' '29%' '84%' '69%' '68%' '38%' '35%' '52%' '76%' '72%' '14%' '65%'
 '55%' '74%' '62%' '21%' '47%' '61%' '13%' '46%' '66%' '10%' '26%']
Présence de photo de profil : ['t' nan 'f']
Conditions d'annulation : ['flexible' 'strict' 'moderate' 'super_strict_30' 'super_strict_60']
Identité vérifiée : ['f' 't' nan]
Réservation en ligne : ['t' 'f']
Villes : ['LA' 'NYC' 'DC' 'SF' 'Chicago' 'Boston']

Pourcentage par colonnes des valeurs nulles (celles qu'on peut transformer en colonnes bool)

In [6]:
n = len(airbnb)

print(f"Valeurs nulles dans instant_bookable :{sum(airbnb['instant_bookable'].isna())/n}")
print(f"Valeurs nulles dans host_profile_picture :{sum(airbnb['host_has_profile_pic'].isna())/n}")
print(f"Valeurs nulles dans host_verified_identity :{sum(airbnb['host_identity_verified'].isna())/n}")
#print(f"Valeurs nulles dans instant_bookable :{sum(airbnb['instant_bookable'].isna())/n}")
#print(f"Valeurs nulles dans instant_bookable :{sum(airbnb['instant_bookable'].isna())/n}")

Valeurs nulles dans instant_bookable :0.0
Valeurs nulles dans host_profile_picture :0.0025186651074930286
Valeurs nulles dans host_verified_identity :0.0025186651074930286

# Entraînement

### Remplacer le type de propriété par un indice, cela permet à l’algo de l’utiliser

In [7]:
class CustomTransformation():

    def __init__(self):
        """
        Class simple pour convertir les type de propriétés en des indices numériques, utilisable pour un algo de machine learning
        """

        self.fitted = False # Indique si fit_transform a été utilisé, pour éviter d’utiliser transform sans que fit ait été appelé
        self.property2index = dict() # Dictionnaire qui va convertir le nom en indice
        self.max_index = 0 # Indique le dernier indice de la propriété.

    def fit_transform(self, dataset):

        self.fitted = True

        # Récupère les types de propriété (maison, appart etc...)
        properties = dataset["property_type"].unique()
        print("Tous les types de propriétés : ", properties)

        self.property2index = {prop:i for (i, prop) in enumerate(properties)}
        self.max_index = max(list(self.property2index.values()))

        # transform
        return self.transform(dataset)
    
    def transform(self, dataset):
        # Transform les propriétés en indice
        dataset.loc[:, "property_type"] = dataset["property_type"].replace(self.property2index)


        # Ligne un peu moche qui fait en sorte de remplacer les lignes qui ont des noms de logement qui n’était pas dans l’entrainement
        dataset.loc[dataset["property_type"].map(type).eq(str), "property_type"] = np.nan

        
        # remplace les valeurs null
        dataset[dataset.bathrooms.isna()] = 0
        dataset[dataset.accommodates.isna()] = 0
        dataset[dataset.property_type.isna()] = self.max_index + 1
        return dataset

In [8]:
features_transformer = CustomTransformation()

airbnb.head()
airbnb_train = features_transformer.fit_transform(airbnb)
airbnb_train.head()

Tous les types de propriétés :  ['House' 'Apartment' 'Townhouse' 'Guest suite' 'Condominium' 'Timeshare'
 'Chalet' 'Guesthouse' 'Bungalow' 'Loft' 'In-law' 'Boat' 'Dorm' 'Other'
 'Bed & Breakfast' 'Camper/RV' 'Villa' 'Boutique hotel' 'Cabin' 'Hostel'
 'Hut' 'Yurt' 'Serviced apartment' 'Castle' 'Vacation home' 'Tent' 'Cave'
 'Tipi' 'Earth House' 'Island' 'Treehouse']

/var/folders/bb/zzg0xqxx14n56mdyj0ynd9xh0000gn/T/ipykernel_56236/2886256945.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset.loc[:, "property_type"] = dataset["property_type"].replace(self.property2index)
/var/folders/bb/zzg0xqxx14n56mdyj0ynd9xh0000gn/T/ipykernel_56236/2886256945.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset[dataset.bathrooms.isna()] = 0

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,last_review,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5708593,4.317488,0,Private room,"{TV,""Wireless Internet"",Kitchen,""Free parking ...",3,1.0,Real Bed,flexible,False,...,NaN,33.782712,-118.134410,Island style Spa Studio,Long Beach,0,NaN,90804,0.0,2.0
1,14483613,4.007333,0,Private room,"{""Wireless Internet"",""Air conditioning"",Kitche...",4,2.0,Real Bed,strict,False,...,2017-09-17,40.705468,-73.909439,"Beautiful and Simple Room W/2 Beds, 25 Mins to...",Ridgewood,38,86.0,11385,1.0,2.0
2,10412649,7.090077,1,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",6,2.0,Real Bed,flexible,False,...,NaN,38.917537,-77.031651,2br/2ba luxury condo perfect for infant / toddler,U Street Corridor,0,NaN,20009,2.0,2.0
3,17954362,3.555348,0,Private room,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",1,1.0,Real Bed,flexible,True,...,2017-09-29,40.736001,-73.924248,Manhattan view from Queens. Lovely single room .,Sunnyside,19,96.0,11104,1.0,1.0
4,9969781,5.480639,0,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,moderate,True,...,2017-08-28,37.744896,-122.430665,Zen Captured Noe Valley House,Noe Valley,15,96.0,94131,2.0,2.0

In [9]:
class FeatureSelection():

    def __init__(self):
        """
        Class simple pour juste garder les colonnes qui nous intéresse
        N'a pas forcément l'air nécessaire, mais c'est pour être sur que j'applique bien le même process au train et au test
        """

    def fit_transform(self, dataset, y=None):
        return self.transform(dataset)
    
    def transform(self, dataset):
        new_dataset = dataset[["property_type", "accommodates", "bathrooms"]].copy()

        for col in new_dataset.columns:
            new_dataset[col] = pd.to_numeric(new_dataset[col]) # Converti tout en nombre
        return new_dataset
    
feature_selector = FeatureSelection()

airbnb_train = feature_selector.transform(airbnb)
airbnb_train.head()

   property_type  accommodates  bathrooms
0              0             3        1.0
1              0             4        2.0
2              1             6        2.0
3              0             1        1.0
4              0             4        1.0

### Apprentissage

In [10]:
from sklearn.model_selection import train_test_split

# Vous avez le droit d’utiliser les Pipeline et transform de sklearn : 
# https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html
features_transformer = CustomTransformation()
feature_selector = FeatureSelection()

airbnb = pd.read_csv("data/airbnb_train.csv")

airbnb_train = features_transformer.fit_transform(airbnb)
airbnb_train = feature_selector.transform(airbnb_train)

X = airbnb_train.copy()
y = airbnb["log_price"]

# train cross validation
X_train, X_test, y_train, y_test = train_test_split(X, y)

Tous les types de propriétés :  ['House' 'Apartment' 'Townhouse' 'Guest suite' 'Condominium' 'Timeshare'
 'Chalet' 'Guesthouse' 'Bungalow' 'Loft' 'In-law' 'Boat' 'Dorm' 'Other'
 'Bed & Breakfast' 'Camper/RV' 'Villa' 'Boutique hotel' 'Cabin' 'Hostel'
 'Hut' 'Yurt' 'Serviced apartment' 'Castle' 'Vacation home' 'Tent' 'Cave'
 'Tipi' 'Earth House' 'Island' 'Treehouse']

/var/folders/bb/zzg0xqxx14n56mdyj0ynd9xh0000gn/T/ipykernel_56236/2886256945.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset.loc[:, "property_type"] = dataset["property_type"].replace(self.property2index)
/var/folders/bb/zzg0xqxx14n56mdyj0ynd9xh0000gn/T/ipykernel_56236/2886256945.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset[dataset.bathrooms.isna()] = 0

Le score R2 est un score de regression, il vaut 1 si la prédiction est parfaite, 0 si la valeur prédite est la moyenne de $y$. Et des scores négatifs si la prédiction est moins bonne que prédire la moyenne (donc vraiment mauvais)

In [11]:
from sklearn.svm import LinearSVR
from sklearn.metrics import r2_score

model = LinearSVR()

model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)


print(f"Score en entrainenement : {r2_score(y_true=y_train, y_pred=y_pred_train)}")
print(f"Score en cross validation : {r2_score(y_true=y_test, y_pred=y_pred_test)}")

Score en entrainenement : 0.3239255202436162
Score en cross validation : 0.31606866380901655

/Users/amyrazafi/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

## Prédiction sur le fichier de test

In [12]:
airbnb_test = pd.read_csv("airbnb_test.csv")

# J’applique le même traitement que mon fichier entraînement
final_X_test = features_transformer.transform(airbnb_test)
final_X_test = feature_selector.transform(final_X_test)

final_X_test.tail()

FileNotFoundError: [Errno 2] No such file or directory: 'airbnb_test.csv'

In [ ]:
y_final_prediction = model.predict(final_X_test)
print(y_final_prediction)

## Sauvegarde dans le fichier de prédiction

In [ ]:
prediction_example = pd.read_csv("prediction_example.csv")
prediction_example["logpred"] = y_final_prediction

prediction_example.to_csv("MaPredictionFinale.csv", index=False) # index=False pour éviter d’ajouter l’index interne à pandas
# Voilà !

## Test de votre fichier

In [ ]:
def estConforme(monFichier_csv):
    votre_prediction = pd.read_csv(monFichier_csv)

    fichier_exemple = pd.read_csv("prediction_example.csv")

    assert votre_prediction.columns[1] == fichier_exemple.columns[1], f"Attention, votre colonne de prédiction doit s'appeler {fichier_exemple.columns[1]}, elle s'appelle '{votre_prediction.columns[1]}'"
    assert len(votre_prediction) == len(fichier_exemple), f"Attention, vous devriez avoir {len(fichier_exemple)} prédiction dans votre fichier, il en contient '{len(votre_prediction)}'"

    assert np.all(votre_prediction.iloc[:,0] == fichier_exemple.iloc[:, 0])

    print("Fichier conforme!")

estConforme("MaPredictionFinale.csv")

# Ce que je vais faire de mon côté

In [ ]:
# Vous n’avez pas accès à ce fichier, c’est normal, ce sont les vrais prédictions
# ===============================================================================
# true_test = pd.read_csv("../true_prediction.csv") 
# ==========================================================

# votre_prediction = pd.read_csv("MaPredictionFinale.csv")["logpred"]
# print(r2_score(y_pred=votre_prediction, y_true=true_test["log_price"]))

# votre_prediction = pd.read_csv("prediction_example.csv")["logpred"] # Devrait avoir ~0
# print(r2_score(y_pred=votre_prediction, y_true=true_test["log_price"]))